CREATE TABLE IF NOT EXISTS whopipe_video_views (
    view_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    video_name TEXT NOT NULL,
    region TEXT NOT NULL,
    date_viewed TIMESTAMP DEFAULT now() NOT NULL
);

DROP TYPE IF EXISTS department;
CREATE TYPE department AS ENUM (
    'Electronics',
    'Cleaning',
    'Grocery',
    'Furniture',
    'Stationery',
    'Clothing',
    'DIY',
    'Sports',
    'Homeware',
    'Games',
    'Transport'
);

CREATE TABLE IF NOT EXISTS amazong_products (
    product_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    price decimal(12,2) NOT NULL,
    image TEXT,
    category department NOT NULL
);

-- **SCRIPT IS PERFORMING 3 TRANSACTIONS**

-- 1st transaction:
-- creates a table (whopipe_video_views) => which has 4 columns
-- Note: IF NOT EXISTS  => prevents CREATE TABLE from being attempted when table already exists

-- 2nd transaction:
-- creates a new type called department => which has ENUM
-- ENUM => a list of options that may be used by columns (which have this new type) in a table
-- CREATE TYPE => doesn't support IF NOT EXISTS so instead we remove the typed if it doesn't exist 1st

-- 3rd transaction:
-- creates a table called amazong_products => which as 5 columns 
-- price => set to a decimal which can be 12 in "precision" & 2 decimal points
-- category => has type department - when we insert row into amazong_product table
-- ... thier value for category would need to be one of those listed in ENUM for department
-- Ex: If 'Electronics' is used as the value its fine - if 'Foo' is used as a value it won't work (not in ENUM list of poss. values)